---
title: "Examples Panda MCMC"
author: "Florian Hartig"
output: html_document
---

Loading the package and the functions

```{r, warning=F}
require(RPANDA)
source("../R/fit_bd.R")
source("../R/fit_env.R")
```


```{r}
data(Cetacea)
tot_time<-max(node.age(Cetacea)$ages)
```

# Constant birth rate model

Fit the pure birth model (no extinction) with a constant speciation rate


```{r, echo=F, warning=F}
f.lamb <-function(t,y){y[1]}
f.mu<-function(t,y){0}
lamb_par<-c(0.09)
mu_par<-c()

prior = BayesianTools::createUniformPrior(lower = c(0), upper = c(1))

result_cst <- fit_bd(Cetacea,tot_time,f.lamb,f.mu,lamb_par,mu_par, f=87/89,cst.lamb=TRUE,fix.mu=TRUE,dt=1e-3, mcmc = F, mcmcSettings = list(iterations = 3000), prior = prior)
```

The MCMC results are stored in result result_cst$mcmc

```{r}
result_cst$mcmc
```


```{r}
plot(result_cst$mcmc)
summary(result_cst$mcmc)
DIC(result_cst$mcmc)
#marginalLikelihood(result_cst$mcmc)
```


# Time-dependent birth rate model

```{r, warning=F}
f.lamb <-function(t,y){y[1] * exp(y[2] * t)}
f.mu<-function(t,y){0}
lamb_par<-c(0.05, 0.01)
mu_par<-c()

prior = BayesianTools::createUniformPrior(lower = c(0,-0.5), upper = c(1,0.5))

result_exp <- fit_bd(Cetacea,tot_time,f.lamb,f.mu,lamb_par,mu_par,f=87/89,expo.lamb=TRUE,fix.mu=TRUE,dt=1e-3, mcmc = T, mcmcSettings = list(iterations = 5000), prior = prior)
```

```{r}
plot(result_exp$mcmc, start = 2500)
summary(result_exp$mcmc, start = 2500)
marginalPlot(result_exp$mcmc, start = 2500)
correlationPlot(result_exp$mcmc, start = 2500)
DIC(result_exp$mcmc, start = 2500)
#marginalLikelihood(result_exp$mcmc, start = 2500)
```

# Environmental-dependent birth rate model

```{r}

data(Cetacea)
tot_time<-max(node.age(Cetacea)$ages)
data(InfTemp)
dof<-smooth.spline(InfTemp[,1], InfTemp[,2])$df

# Fits a model with lambda varying as an exponential function of temperature
# and mu fixed to 0 (no extinction).  Here t stands for time and x for temperature.
f.lamb <-function(t,x,y){y[1] * exp(y[2] * x)}
f.mu<-function(t,x,y){0}
lamb_par<-c(0.10, 0.01)
mu_par<-c()

prior = BayesianTools::createUniformPrior(lower = c(0,-0.2), upper = c(0.5,0.2))

result_env <- fit_env(Cetacea,InfTemp,tot_time,f.lamb,f.mu,lamb_par,mu_par, f=87/89,fix.mu=TRUE,df=dof,dt=1e-3, mcmc = T, mcmcSettings = list(iterations = 5000), prior = prior)
```



```{r}
plot(result_env$mcmc, start = 2500)
summary(result_env$mcmc, start = 2500)
marginalPlot(result_env$mcmc, start = 2500)
correlationPlot(result_env$mcmc, start = 2500)
DIC(result_env$mcmc, start = 2500)
#marginalLikelihood(result_env$mcmc, start = 2500)
```


