include("ETR2.jl")
include("get_parent_rates_ETR2.jl")
include("change_edges_ETR2.jl")
include("gibbs_ETR2.jl")
include("update_edges_ETR2.jl")
include("mcmc_ETR2.jl")
include("extract_from_ETR2.jl")
include("LTT_ETR2.jl")
include("gelman.jl")
print("loading mean_rates")
include("rates_through_time.jl")
println(" done")
